Update UI to match theme
AY2324S1-CS2103T-F11-2/tp pull request #142
Opened 2023-10-24 12:54 UTC by tllshan

2023-10-27 01:17 UTC, p-xp requested changes
Overall, really nice work on the design, and the app looks good 😄 Just some very minor nits to address.

2023-10-27 01:17 UTC, p-xp commented on src/main/resources/view/MainWindow.fxml
>              <StackPane fx:id="guestListPanelPlaceholder" VBox.vgrow="ALWAYS" />
The spacing on top of guestlist / vendorlist is inconsistent with the spacing between elements used throughout the rest of the app. It is narrower and thus seems slightly cramped. Would it be possible to make the spacing the same as every other place (e.g. the spacing between total count and rsvp status panel, and rsvp status and dietary panel)

2023-10-27 01:17 UTC, p-xp commented on src/main/resources/view/MainWindow.fxml
>          <StackPane fx:id="statusbarPlaceholder" prefWidth="405.0" VBox.vgrow="NEVER" />
Leaving the comment here as I'm not sure what's causing the issue. The application doesn't scale with size.
![image](https://github.com/AY2324S1-CS2103T-F11-2/tp/assets/99188356/8560eac2-7700-4385-b375-005858faf9d0)

2023-10-27 01:17 UTC, p-xp commented on src/main/resources/view/MainWindow.fxml
> +        <HBox HBox.hgrow="ALWAYS" prefWidth="400"  style="-fx-background-color: #f1e5e5">
Leaving this comment here as I can't comment on unedited portions.

The current menu bar design seems quite incongruous with the rest of the application, in terms of: font size, background colour (not sure if I'm seeing correctly but it seems to have a slight gradient), width.

2023-10-31 02:02 UTC, p-xp approved these changes
The dietary requirements panel looks a little squashed right now, would be quite difficult to view once we have more. Is it possible to remove the guest and vendor count box so that we have more vertical space for DR panel?
The guest and vendor count can be included at the top of the respective lists -- e.g. Guest(7), Vendor(3)

If this cannot be implemented in time for the demo, I am happy to merge as is.

2023-10-31 02:45 UTC, keaganpzh commented
> The dietary requirements panel looks a little squashed right now, would be quite difficult to view once we have more. Is it possible to remove the guest and vendor count box so that we have more vertical space for DR panel? The guest and vendor count can be included at the top of the respective lists -- e.g. Guest(7), Vendor(3)
> 
> If this cannot be implemented in time for the demo, I am happy to merge as is.

In the interest of time, I can take over these tasks. For now, let's merge this PR.

2023-10-31 02:48 UTC, merged